/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "media",
  theme: {
    extend: {
      fontFamily: {
        mono: ['"JetBrains Mono"', "monospace"],
        sans: ['"Geist"', '"Inter"', "sans-serif"],
        display: ['"Syne"', "sans-serif"],
      },
      colors: {
        mocha: {
          base: "#1e1e2e",
          mantle: "#181825",
          crust: "#11111b",
          surface0: "#313244",
          surface1: "#45475a",
          surface2: "#585b70",
          overlay0: "#6c7086",
          overlay1: "#7f849c",
          overlay2: "#9399b2",
          subtext0: "#a6adc8",
          subtext1: "#bac2de",
          text: "#cdd6f4",
          lavender: "#b4befe",
          blue: "#89b4fa",
          sapphire: "#74c7ec",
          sky: "#89dceb",
          teal: "#94e2d5",
          green: "#a6e3a1",
          yellow: "#f9e2af",
          peach: "#fab387",
          maroon: "#eba0ac",
          red: "#f38ba8",
          mauve: "#cba6f7",
          pink: "#f5c2e7",
          flamingo: "#f2cdcd",
          rosewater: "#f5e0dc",
        },
        latte: {
          base: "#eff1f5",
          mantle: "#e6e9ef",
          crust: "#dce0e8",
          surface0: "#ccd0da",
          surface1: "#bcc0cc",
          surface2: "#acb0be",
          overlay0: "#9ca0b0",
          overlay1: "#8c8fa1",
          overlay2: "#7c7f93",
          subtext0: "#6c6f85",
          subtext1: "#5c5f77",
          text: "#4c4f69",
          lavender: "#7287fd",
          blue: "#1e66f5",
          sapphire: "#209fb5",
          sky: "#04a5e5",
          teal: "#179299",
          green: "#40a02b",
          yellow: "#df8e1d",
          peach: "#fe640b",
          maroon: "#e64553",
          red: "#d20f39",
          mauve: "#8839ef",
          pink: "#ea76cb",
          flamingo: "#dd7878",
          rosewater: "#dc8a78",
        },
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease forwards",
        "slide-up": "slideUp 0.6s ease forwards",
        "slide-in-left": "slideInLeft 0.5s ease forwards",
        "glow-pulse": "glowPulse 3s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideInLeft: {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 8px 0px rgba(243,139,168,0.3)" },
          "50%": { boxShadow: "0 0 24px 4px rgba(243,139,168,0.6)" },
        },
      },
    },
  },
  plugins: [],
};
